spring:
  datasource:
    url: jdbc:h2:mem:test
    username: superuser
    password: supersecret
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect